@startuml
actor Shopper as Shopper
Shopper -> FarmacyFamilyPortal: Selects 'Create Account'
Shopper -> FarmacyFamilyPortal: Enters account information with Fridge ID
Shopper -> FarmacyFamilyPortal: Select sharing options
FarmacyFamilyPortal -> CDM: Creates customer profile
FarmacyFamilyPortal -> Firestore: Create supplemental user data
@enduml