@startuml
actor Shopper as Shopper
Shopper -> Fridge: Buys a meal
Fridge -> FarmacyFoods: Request a meal
FarmacyFoods -> TDM: Submit transaction
TDM -> DataProcesser: Submit transaction data
DataProcesser -> DataLake: Store tranaction data
Looker -> DataLake: Queries data about purchases with respect to geography
@enduml